name: Upload Python Package

on: [release]

jobs:
  deploy:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Build
      run: |
        python -m pip install --upgrade pip
        pip install build
        python -m build
    - name: Upload to Public PyPi
      run: |
        pip install twine
        twine upload --skip-existing dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
